import { createStore } from 'vuex';
import actions from './actions';
import mutations from './mutations';
import getters from './getters';

export default createStore({
   state: {
      products: [
         {
            id: 1,
            url: '#',
            title: 'Syltherine',
            text: 'Stylish cafe chair',
            labels: '',
            image: '1.jpg',
            price: '2.500.000',
            priceOld: '3.500.000',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
         {
            id: 2,
            url: '#',
            title: 'Leviosa',
            text: 'Stylish cafe chair',
            labels: '',
            image: '2.jpg',
            price: '2.500.000',
            priceOld: '',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
         {
            id: 3,
            url: '#',
            title: 'Lolito',
            text: 'Luxury big sofa',
            labels: '',
            image: '3.jpg',
            price: '7.000.000',
            priceOld: '14.000.000',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
         {
            id: 4,
            url: '#',
            title: 'Respira',
            text: 'Minimalist fan',
            labels: '',
            image: '4.jpg',
            price: '500.000',
            priceOld: '',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
         {
            id: 5,
            url: '#',
            title: 'Grifo',
            text: 'Night lamp',
            labels: '',
            image: '5.jpg',
            price: '1.500.000',
            priceOld: '',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
         {
            id: 6,
            url: '#',
            title: 'Muggo',
            text: 'Small mug',
            labels: [
               {
                  type: 'sale',
                  value: '-50%',
               },
               {
                  type: 'new',
                  value: 'New',
               },
            ],
            image: '6.jpg',
            price: '150.000',
            priceOld: '',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
         {
            id: 7,
            url: '#',
            title: 'Pingky',
            text: 'Cute bed set',
            labels: [
               {
                  type: 'sale',
                  value: '-50%',
               },
            ],
            image: '7.jpg',
            price: '7.000.000',
            priceOld: '14.500.000',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
         {
            id: 8,
            url: '#',
            title: 'Potty',
            text: 'Minimalist flower pot',
            labels: [
               {
                  type: 'new',
                  value: 'New',
               },
            ],
            image: '8.jpg',
            price: '500.000',
            priceOld: '',
            shareUrl: '',
            likeUrl: '',
            quantity: 0,
         },
      ],
      cart: [],
      deleted: [],
      width: 0,
      height: 0,
   },
   getters,
   mutations,
   actions,
   modules: {},
});
